version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./flag.txt:/root/flag.txt
    tty: true
    stdin_open: true
